export const LOAD_SHEET_DATA = 'LOAD_SHEET_DATA';
export const RESET_SHEET_DATA = 'RESET_SHEET_DATA';
export const ADD_SHEET_ROW = 'ADD_SHEET_ROW';
export const ADD_SHEET_COLUMN = 'ADD_SHEET_COLUMN';
export const SET_COLUMN_TITLE = 'SET_COLUMN_TITLE';
export const SET_CELL_VALUE = 'SET_CELL_VALUE';
